import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Google Clone generated by Shivam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <html>
        <link rel="icon" href="/favicon.svg" />
      </html>

      <body className="relative min-h-screen">
        {children}
        <Footer />
      </body>
    </html>
  );
}
