import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Google Clone generated by Shivam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <html>
        <link rel="icon" href="/favicon.svg" />
      </html>
      {/* <Head>
        <link rel="icon" href="/favicon.svg" />
      </Head> */}
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
